env:
  global:
    - CC_TEST_REPORTER_ID=299cc3ce9c5c40f81f6743045e30dddfba3525c32228d9ebffcb8770839b73a8
language: node_js
node_js:
  - "8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
    - npm run ci
    - npm run lint
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
